akka/akka-persistence-spanner

- build.sbt
- journal/src/main/resources/reference.conf
- journal/src/main/scala/akka/persistence/spanner/SpannerJournal.scala
- journal/src/main/scala/akka/persistence/spanner/SpannerSettings.scala
- journal/src/main/scala/akka/persistence/spanner/internal/SessionPool.scala
- journal/src/test/scala/akka/persistence/spanner/ExampleSpec.scala
- journal/src/test/scala/akka/persistence/spanner/SpannerSpec.scala
- journal/src/test/scala/akka/persistence/spanner/internal/AbstractStubbedSpannerClient.scala
- journal/src/test/scala/akka/persistence/spanner/internal/SessionPoolSpec.scala
- journal/src/test/scala/akka/persistence/spanner/internal/SessionPoolStubbedSpec.scala
Needs more work but be good to get this in so we can work in parallel on everything else
Refs #4
> Initial session pool

- journal/src/main/scala/akka/persistence/spanner/SpannerJournal.scala
For the case when the actor crashes while a write is in progrss
> Delay sequence nr query until any pending write is finished

- journal/src/main/resources/reference.conf
- journal/src/main/scala/akka/persistence/spanner/SpannerJournal.scala
- journal/src/main/scala/akka/persistence/spanner/SpannerSettings.scala
- journal/src/main/scala/akka/persistence/spanner/internal/SessionPool.scala
- journal/src/test/scala/akka/persistence/spanner/internal/SessionPoolStubbedSpec.scala
> Session pool supervision and cleanup

- .travis.yml
- journal/src/main/resources/reference.conf
- journal/src/main/scala/akka/persistence/spanner/SpannerSettings.scala
- journal/src/main/scala/akka/persistence/spanner/internal/SpannerGrpcClient.scala
> Fixed or ticketified remaining TODOs

- README.md
- docs/src/main/paradox/contributing.md
- docs/src/main/paradox/developing.md
- docs/src/main/paradox/getting-started.md
- docs/src/main/paradox/index.md
- docs/src/main/paradox/journal.md
- docs/src/main/paradox/overview.md
> Basic docs for initial release

- docs/src/main/paradox/contributing.md
- journal/src/main/scala/akka/persistence/spanner/SpannerSettings.scala
- journal/src/test/scala/akka/persistence/spanner/SpannerSpec.scala
- journal/src/test/scala/akka/persistence/spanner/internal/SessionPoolSpec.scala
> Ability to run tests against real spanner

- journal/src/main/scala/akka/persistence/spanner/SpannerInteractions.scala
- journal/src/main/scala/akka/persistence/spanner/SpannerJournal.scala
- journal/src/main/scala/akka/persistence/spanner/internal/SessionPool.scala
- journal/src/main/scala/akka/persistence/spanner/internal/SpannerGrpcClient.scala
- journal/src/test/resources/logback-test.xml
- journal/src/test/scala/akka/persistence/spanner/SpannerJournalPerfSpec.scala
- journal/src/test/scala/akka/persistence/spanner/SpannerSpec.scala
> JournalPerfSpec and some other small improvements here and there

- docs/src/main/paradox/journal.md
- journal/src/main/resources/reference.conf
- journal/src/main/scala/akka/persistence/spanner/SpannerJournal.scala
- journal/src/main/scala/akka/persistence/spanner/SpannerReadJournalProvider.scala
- journal/src/main/scala/akka/persistence/spanner/internal/SpannerGrpcClient.scala
- journal/src/main/scala/akka/persistence/spanner/internal/SpannerGrpcClientExtension.scala
- journal/src/main/scala/akka/persistence/spanner/javadsl/SpannerReadJournal.scala
- journal/src/main/scala/akka/persistence/spanner/scaladsl/SpannerReadJournal.scala
- journal/src/test/scala/akka/persistence/spanner/SpannerSpec.scala
- journal/src/test/scala/akka/persistence/spanner/javadsl/SpannerReadJournalSpec.scala
- journal/src/test/scala/akka/persistence/spanner/scaladsl/SpannerReadJournalSpec.scala
Doesn't implement anything yet, just so we can work on the different queries in parallel 
Also includes creating a single grpc client across all parts of the plugin
> Initial query journal

- journal/src/main/resources/reference.conf
- journal/src/main/scala/akka/persistence/spanner/SpannerSettings.scala
- journal/src/main/scala/akka/persistence/spanner/internal/SpannerGrpcClient.scala
- journal/src/test/scala/akka/persistence/spanner/internal/StubbedSpannerGrpcClientSpec.scala
> Retry writes on ABORTED failure

- docs/src/main/paradox/index.md
- docs/src/main/paradox/snapshots.md
- journal/src/main/resources/reference.conf
- journal/src/main/scala/akka/persistence/spanner/SpannerJournal.scala
- journal/src/main/scala/akka/persistence/spanner/SpannerSettings.scala
- journal/src/main/scala/akka/persistence/spanner/SpannerSnapshotStore.scala
- journal/src/main/scala/akka/persistence/spanner/internal/SessionPool.scala
- journal/src/main/scala/akka/persistence/spanner/internal/SpannerGrpcClient.scala
- journal/src/main/scala/akka/persistence/spanner/internal/SpannerJournalInteractions.scala
- journal/src/main/scala/akka/persistence/spanner/internal/SpannerSnapshotInteractions.scala
- journal/src/main/scala/akka/persistence/spanner/internal/SpannerUtils.scala
- journal/src/test/resources/logback-test.xml
- journal/src/test/scala/akka/persistence/spanner/SpannerSnapshotStoreSpec.scala
- journal/src/test/scala/akka/persistence/spanner/SpannerSpec.scala
- journal/src/test/scala/akka/persistence/spanner/internal/SpannerUtilsSpec.scala
> Snapshot store

- .travis.yml
- build.sbt
- journal/src/main/resources/reference.conf
- journal/src/main/scala/akka/persistence/spanner/SpannerInteractions.scala
- journal/src/main/scala/akka/persistence/spanner/SpannerOffset.scala
- journal/src/main/scala/akka/persistence/spanner/SpannerSettings.scala
- journal/src/main/scala/akka/persistence/spanner/internal/ContinuousQuery.scala
- journal/src/main/scala/akka/persistence/spanner/internal/RowCollector.scala
- journal/src/main/scala/akka/persistence/spanner/internal/SessionPool.scala
- journal/src/main/scala/akka/persistence/spanner/internal/SpannerGrpcClient.scala
- journal/src/main/scala/akka/persistence/spanner/javadsl/SpannerReadJournal.scala
- journal/src/main/scala/akka/persistence/spanner/scaladsl/SpannerReadJournal.scala
- journal/src/test/resources/logback-test.xml
- journal/src/test/scala/akka/persistence/spanner/CborSerializable.scala
- journal/src/test/scala/akka/persistence/spanner/EventsByTagSpec.scala
- journal/src/test/scala/akka/persistence/spanner/PersistenceIdsQuerySpec.scala
- journal/src/test/scala/akka/persistence/spanner/SpannerJournalPerfSpec.scala
- journal/src/test/scala/akka/persistence/spanner/SpannerSpec.scala
- journal/src/test/scala/akka/persistence/spanner/TestActors.scala
- journal/src/test/scala/akka/persistence/spanner/internal/ContinuousQuerySpec.scala
- journal/src/test/scala/akka/persistence/spanner/internal/StubbedSpannerGrpcClientSpec.scala
- journal/src/test/scala/akka/persistence/spanner/javadsl/SpannerReadJournalSpec.scala
- journal/src/test/scala/akka/persistence/spanner/scaladsl/SpannerReadJournalSpec.scala
- project/Dependencies.scala
> Events by tag & all persistence ids

- .travis.yml
- project/Dependencies.scala
- testLatestAkkaSnapshot.sh
> Cron for testing with latest akka

- build.sbt
- example/README.md
- example/src/main/resources/common.conf
- example/src/main/resources/local-emulator.conf
- example/src/main/resources/local.conf
- example/src/main/resources/logback.xml
- example/src/main/scala/akka/persistence/spanner/example/CborSerializable.scala
- example/src/main/scala/akka/persistence/spanner/example/ConfigurablePersistentActor.scala
- example/src/main/scala/akka/persistence/spanner/example/EventProcessorStream.scala
- example/src/main/scala/akka/persistence/spanner/example/LoadGenerator.scala
- example/src/main/scala/akka/persistence/spanner/example/Main.scala
- example/src/main/scala/akka/persistence/spanner/example/ReadSide.scala
- example/src/main/scala/akka/persistence/spanner/example/ReadSideTopic.scala
- example/src/main/scala/akka/persistence/spanner/example/Reporter.scala
- journal/src/main/scala/akka/persistence/spanner/internal/ContinuousQuery.scala
- journal/src/main/scala/akka/persistence/spanner/internal/SpannerGrpcClient.scala
- journal/src/main/scala/akka/persistence/spanner/internal/SpannerJournalInteractions.scala
- journal/src/main/scala/akka/persistence/spanner/internal/SpannerSnapshotInteractions.scala
- journal/src/test/scala/akka/persistence/spanner/PrintSchema.scala
- journal/src/test/scala/akka/persistence/spanner/SpannerSpec.scala
- project/Dependencies.scala
> End to end event by tag example

- journal/src/test/scala/akka/persistence/spanner/EventsByPersistenceIdQuerySpec.scala
> Harden EventsByPersistenceIdQuerySpec

- docs/src/main/paradox/journal.md
- example/src/main/scala/akka/persistence/spanner/example/Main.scala
- journal/src/main/resources/reference.conf
- journal/src/main/scala/akka/persistence/spanner/SpannerSettings.scala
- journal/src/main/scala/akka/persistence/spanner/internal/SpannerJournalInteractions.scala
- journal/src/main/scala/akka/persistence/spanner/internal/SpannerSnapshotInteractions.scala
- journal/src/main/scala/akka/persistence/spanner/scaladsl/SpannerReadJournal.scala
- journal/src/test/scala/akka/persistence/spanner/EventsByTagSpec.scala
- journal/src/test/scala/akka/persistence/spanner/PrintSchema.scala
- journal/src/test/scala/akka/persistence/spanner/SpannerSpec.scala
- journal/src/test/scala/akka/persistence/spanner/TestActors.scala
So that we can index tags. This is the needed schema change will look into secondary index for it next.
References #77
> Separated interleaved table for tags 

- journal/src/test/scala/akka/persistence/spanner/EventsByTagSpec.scala
> Harden EventsByTagSpec

- journal/src/main/scala/akka/persistence/spanner/internal/ContinuousQuery.scala
Swamps the log when debugging, we can re-add if we need them in future.
> Remove debug logging per element in continous query

- journal/src/main/resources/reference.conf
- journal/src/main/scala/akka/persistence/spanner/SpannerSnapshotStore.scala
- journal/src/main/scala/akka/persistence/spanner/internal/ContinuousQuery.scala
- journal/src/main/scala/akka/persistence/spanner/internal/SessionPool.scala
- journal/src/main/scala/akka/persistence/spanner/internal/SpannerGrpcClient.scala
- journal/src/main/scala/akka/persistence/spanner/internal/SpannerGrpcClientExtension.scala
- journal/src/main/scala/akka/persistence/spanner/internal/SpannerJournalInteractions.scala
- journal/src/main/scala/akka/persistence/spanner/internal/SpannerSnapshotInteractions.scala
- journal/src/main/scala/akka/persistence/spanner/internal/SpannerUtils.scala
- journal/src/main/scala/akka/persistence/spanner/javadsl/SpannerReadJournal.scala
- journal/src/main/scala/akka/persistence/spanner/scaladsl/SpannerReadJournal.scala
- journal/src/test/scala/akka/persistence/spanner/EventsByTagSpec.scala
- journal/src/test/scala/akka/persistence/spanner/PersistenceIdsQuerySpec.scala
- journal/src/test/scala/akka/persistence/spanner/SpannerJournalPerfSpec.scala
- journal/src/test/scala/akka/persistence/spanner/internal/ContinuousQuerySpec.scala
- journal/src/test/scala/akka/persistence/spanner/internal/RowCollectorSpec.scala
- journal/src/test/scala/akka/persistence/spanner/internal/SessionPoolStubbedSpec.scala
- journal/src/test/scala/akka/persistence/spanner/internal/StubbedSpannerGrpcClientSpec.scala
References #63 
Also optimized imports/removed unused
> Fix config indentation

- journal/src/main/resources/reference.conf
- journal/src/main/scala/akka/persistence/spanner/internal/SpannerSerializer.scala
- journal/src/test/scala/akka/persistence/spanner/internal/SpannerSerializerSpec.scala
* needed for offset storage in Akka Projections
> Akka serializer for the SpannerOffset

- journal/src/main/resources/reference.conf
- journal/src/main/scala/akka/persistence/spanner/SpannerObjectStore.scala
- journal/src/main/scala/akka/persistence/spanner/SpannerSettings.scala
- journal/src/main/scala/akka/persistence/spanner/internal/SpannerGrpcClient.scala
- journal/src/main/scala/akka/persistence/spanner/internal/SpannerGrpcClientExtension.scala
- journal/src/main/scala/akka/persistence/spanner/internal/SpannerObjectInteractions.scala
- journal/src/main/scala/akka/persistence/spanner/internal/SpannerSnapshotInteractions.scala
- journal/src/test/scala/akka/persistence/spanner/PrintSchema.scala
- journal/src/test/scala/akka/persistence/spanner/SpannerObjectStoreSpec.scala
- journal/src/test/scala/akka/persistence/spanner/SpannerSpec.scala
> Basic k/v table implementation

- journal/src/main/scala/akka/persistence/spanner/SpannerObjectStore.scala
- journal/src/main/scala/akka/persistence/spanner/internal/SpannerObjectInteractions.scala
- journal/src/test/scala/akka/persistence/spanner/SpannerObjectStoreSpec.scala
> Start object sequence numbers at '1'

- .travis.yml
> Use latest jabba

- .scala-steward.conf
> fix: exlude akka from scala-steward

- .travis.yml
Avoiding the annoying jabba outages
> Use JDK 8 from debian package

- build.sbt
- docs/src/main/paradox/durable-state-store.md
- docs/src/main/paradox/index.md
- journal/src/main/resources/reference.conf
- journal/src/main/scala/akka/persistence/spanner/SpannerObjectStore.scala
- journal/src/main/scala/akka/persistence/spanner/SpannerSettings.scala
- journal/src/main/scala/akka/persistence/spanner/internal/SpannerObjectInteractions.scala
- journal/src/main/scala/akka/persistence/spanner/state/SpannerDurableStateStoreProvider.scala
- journal/src/main/scala/akka/persistence/spanner/state/javadsl/SpannerDurableStateStore.scala
- journal/src/main/scala/akka/persistence/spanner/state/scaladsl/SpannerDurableStateStore.scala
- journal/src/test/scala/akka/persistence/spanner/SpannerDurableStateStoreSpec.scala
- journal/src/test/scala/akka/persistence/spanner/SpannerObjectStoreSpec.scala
- journal/src/test/scala/akka/persistence/spanner/SpannerSpec.scala
- project/Dependencies.scala
> Durable state store.

- journal/src/main/resources/reference.conf
See https://github.com/akka/akka/issues/31058
> User default-dispatcher
